### ISSUE TITLE
Failed to get OpenProject notifications✖

### ISSUE THREAD

**Issue by robse030** [eneiluj/integration_openproject#4]
Hi,
I cannot connect to the openproject server with my fresh nextcloud installation.

The nextcloud log:
```
[integration_openproject] Warning: OpenProject API error : Client error: `GET https://openproject.server.de/api/v3/work_packages?filters=%5B%7B%22status%22%3A%7B%22operator%22%3A%22%21%22%2C%22values%22%3A%5B%2214%22%5D%7D%7D%5D&sortBy=%5B%5B%22updatedAt%22%2C+%22desc%22%5D%5D` resulted in a `400 Bad Request` response:
{"_type":"Error","errorIdentifier":"urn:openproject-org:api:v3:errors:InvalidQuery","message":"Status Filter enthält un (truncated...)


GET /index.php/apps/integration_openproject/notifications
from 10.201.21.184 by rgrosser at 2021-06-21T11:51:25+00:00
```

Kind regards,
Robert

**Comment by eneiluj** [comment]
Hi,

Which version of OpenProject are you using?
How do you connect?
Did you set an application ID and application secret in admin settings and use OAuth?
Or did you just use a personal API key?

Everything works fine for me with OpenProject v11.1.1. I tried your request with my instance and it worked fine.

Your problem is most likely related to the API of your OP instance being different (maybe too old).

**Comment by robse030** [comment]
Hi, 

sorry for the missing informations. I use the following versions:
Nextcloud: 21.0.2
OpenProject: 11.3.2

with personal API keys.

**Comment by eneiluj** [comment]
I updated my OP instance to 11.3.2 and it still works :grin:.

We can see in the error you get that OP complains about the `Status filter which contains a...`.
Could you try to get the full error message? This can be done by manually making a request:

Assuming you are using a GNU/Linux environment.
First you need to generate the authentication header:
``` php
// replace YOUR_API_KEY
php -r 'echo base64_encode("apikey:YOUR_API_KEY");echo "\n";'
```
This will print a base64 string.
Then just make this request:
``` bash
# replace THE_BASE64_STRING by the result of the previous command
curl -H "Authorization: Basic THE_BASE64_STRING" 'https://openproject.server.de/api/v3/work_packages?filters=%5B%7B%22status%22%3A%7B%22operator%22%3A%22%21%22%2C%22values%22%3A%5B%2214%22%5D%7D%7D%5D&sortBy=%5B%5B%22updatedAt%22%2C+%22desc%22%5D%5D'
```

This will print the full response from OP.

In the meantime I will improve the error management in the app.

**Comment by robse030** [comment]
Hi, here is the result: 

`{"_type":"Error","errorIdentifier":"urn:openproject-org:api:v3:errors:InvalidQuery","message":"Status Filter enthält ungültige Werte."}
`

**Comment by eneiluj** [comment]
Everything happens there: https://github.com/eneiluj/integration_openproject/blob/0e25c95066ab2a17b3847bdb2dc75032fb59f4c9/lib/Service/OpenProjectAPIService.php#L199-L201

The only way I could reproduce your issue is by inserting "real" invalid characters in the filter (like `&`).
Could you try to replace the 2 occurrences of `"14"` by `14`?

**Comment by robse030** [comment]
Removing the quotation marks does not solve the problem. It only worked when I commented out the filter. Can the problem be the time zone or the format?

```
         $filters = null;
        //      if ($since) {
        //              date_default_timezone_set('UTC');
        //              $utcTimezone = new \DateTimeZone('-0000');
        //              $nowDt = new \Datetime();
        //              $nowDt->setTimezone($utcTimezone);
        //              $now = $nowDt->format('Y-m-d\TH:i:s\Z');
        //              $filters = '[{"updatedAt":{"operator":"<>d","values":["' . $since . '","' . $now . '"]}},{"status":{"operator":"!","values":["14"]}}]';
        //      } else {
        //              $filters = '[{"status":{"operator":"!","values":["14"]}}]';
        //      }

```

**Comment by eneiluj** [comment]
> It has to be the filters

Yes indeed. The first time this function is called, there is no `$since` so the `else` block is executed. I really don't understand why this would get rejected by your OP instance and not mine...

It is done correctly according to the OP API doc: https://docs.openproject.org/api/filters/#header-filter-syntax-1

I was working with OpenProject people while developing this app and they never complained about such issue... Maybe it's something very specific to your context. A Ruby settings, a webserver setting... I don't know where to go now :grin:.

Let me send you an API key for my instance to confirm the app works (even if this will not help much). Could you send me an email at eneiluj@posteo.net?

**Comment by robse030** [comment]
The problem could be solved by providing openproject as Docker rather than from the packages. 
The problem could be solved by providing openproject as Docker rather than from the packages. It seems, that there are differences here.

**Comment by eneiluj** [comment]
Thanks for the feedback. Good (and sad) to know.
